version: '3.7'
services:
  php:
    container_name: project-name_php_1
    build: docker/php
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - .:/var/www/html
     - ./docker/apache:/etc/apache2/sites-enabled:ro
    networks:
     - appnet
  db:
    container_name: project-name_db_1
    build: docker/postgres
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: project-name
      POSTGRES_DB: project-name
      POSTGRES_USER: project-name
    volumes:
     - data:/var/lib/postgresql/data
    networks:
     - appnet
  redis:
    container_name: project-name_redis_1
    image: redis:alpine
    networks:
      - appnet
  mail:
    container_name: project-name_mail_1
    image: mailhog/mailhog:latest
    ports:
     - "8025:8025"
    networks:
     - appnet
  s3:
    container_name: project-name_s3_1
    image: minio/minio
    command: server --address ":9000" --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - s3:/data
    networks:
      - appnet
    # See README.md
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
  s3:
    driver: "local"
